Cloud bastion
Otus-DevOps-2021-08/Inknex_infra pull request #2
Opened 2021-09-28 19:50 UTC by Inknex

# Выполнено ДЗ №

 - [ ] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
- Создана ветка cloud-bastion
- Поднял два VM Instances в Google Cloud
- Выполнено подключение к VM в VPC через Bastion
- Развернут и настроен VPN сервер

## Как проверить работоспособность VPN:
 - Например, перейти по ссылке https://34.122.81.33.sslip.io/

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2021-09-29 19:08 UTC, mrgreyves requested changes
Здравствуйте!)
![image](https://user-images.githubusercontent.com/34331259/135332989-b832adf4-fdb5-4bee-a3e5-d6717bc3b929.png)

У вас нет тестов, надо их добавить. Возможно вы забыли помержить изменения из предыдущих дз в мастер.
ДЗ возвращаю на доработку

2021-09-29 22:00 UTC, Inknex commented
> Здравствуйте!) ![image](https://user-images.githubusercontent.com/34331259/135332989-b832adf4-fdb5-4bee-a3e5-d6717bc3b929.png)
> 
> У вас нет тестов, надо их добавить. Возможно вы забыли помержить изменения из предыдущих дз в мастер. ДЗ возвращаю на доработку

Я начал делать ДЗ№3 до того как получил апрув по ДЗ№2

2021-09-29 22:12 UTC, Inknex commented
Тесты пройдены

2021-09-30 16:47 UTC, mrgreyves approved these changes
Здравствуйте!)
Какой то странный порядок выполнения дз у вас получился.
Данное дз выполнено корректно, дз принимаю!=)

2021-09-30 19:32 UTC, merged